优化模型转换文档结构；修复路径带空格的 bug；修复模型变量名带有 : 无法转换的 bug (#181)
* fix some spelling mistake

* Update convert.md

* Update README.md

* Update compile.md

* Update cpu_utils.cc

这部分代码貌似源自系统的 `/usr/include/sched.h`，修复 arm linux 下的冲突。
例如
```
/home/ubuntu/TNN/source/tnn/utils/cpu_utils.cc:165:0: warning: "__NCPUBITS" redefined
```

* Update cpu_utils.cc

* Update unit_test.md

* Update quantization.md

* Update quantization.md

* Update quantize.cc

* update api doc

* [UPD]update doc

* fix compile warning

* [BUG]fix potential crash

* add std::sqrt header

* add std::fabs headers

* Update README.md

* update README 统一性能数据，特定芯片模型性能issue记录

* fix compile error

* fix metal compile error

* [UPD]update the doc

* [UPD]update the doc

* [UPD]update the doc

* [UPD]update the doc

* [DOC]update readme

* [FIX]remove bad build.sh

* more stable tanh_ps

ported from https://github.com/Tencent/ncnn/commit/c35bf2f09152608858c87910763a816cb562c28a

* [FIX]fix arm linux demo

* [DOC]update armlinux demo doc

* [DOC]fix arm linux demo doc

* [DOC]update readme typo

* remove unused metal cpu adapter

* handle GetMaxFreqOfCpu second try properly

ported from https://github.com/Tencent/ncnn/commit/69e2693c87a24470a5c9ed12d13c8bced893cadd and https://github.com/Tencent/ncnn/commit/29056398901f9698edbea734ea5ef9beb21094fc

* [DOC]architect change

* update doc from rapid to tnn

* [FIX]fix model check error

* [DOC]update pic

* [DOC]fix readme

* Revert "[DOC]fix readme"

This reverts commit 09b23397d0ddf00d57fbcbc83af156833f77e6ed.

* [ADD]add readthedoc requirements.txt

* Set theme jekyll-theme-cayman

* [MODEL_CHECK][UPD] 1. add align for convert2tnn

* add tools/convert2tnn/build.sh

* [doc]convert model doc change

* [doc]convert model doc change en

* [doc]convert model doc change env2

* [doc]merge updates

* Set theme jekyll-theme-cayman

* add tools/convert2tnn/build.sh

* [CONVERT2TNN][UPD] 1. add args message;

* fix bug

* [CONVERT2TNN][BUG] 1. fix args parse bug;

* change GREATER_EQUAL to GREATER

* fix bug

* [CONVERT2TNN][BUG] 1. change data_dir -> temp_data;

* add interface

* fix bug

* fix bug

* delete redundant code

* modify build.sh

* [UPD]update the doc

* tf2tnn module add model_check

* modify build.sh

* [FIX]fix armlinux opencl build issue

* [OPENCL][BUG] fix BlobConverter bug when input format is N8UC3

* [doc]update tech-solutions

* [OPENCL][CHG] remove some unused opencl api

* [ADD]add new benchmark.cc

* [CHG] change benchmark blob converter and forward api

* [CHG]change test.cc

* fix the bug of model_check

* update benchmark tnn proto

* change download model to github

* modify converter tools' doc

* add feature: specify tensorflow model's input shape

* add onnx_name2tnn_name

* Fix tf2tnn output dir problems

* add ref_file format

* fix bug

* [MODEL_CHECK][BUG]1. fix issue 54;

* [MODEL_CHECK][BUG]1. support to compile static executable modelc_check on android platform;

* [MODEL_CHECK][BUG]1. add reference formate check

* update Model Visualization Netron

* modify converter's doc

* remove redundant code

* modify description

* modify doc

* fix bug

* modify fold_const

* modify fold_const

* modify doc

* modify doc

* modify doc

* fix bug

* sync

* [ONNX2TNN][BUG] 1. fix Issue #68;

* update document of ncnn supported operations

* [TNN][BUG]1. fix issue #78;

* [ONNX2TNN][ADD] add tf-style shufflechannel convert

* [TOOLS][BUG] fix quantization tool running failed

issue #84

* [DOC][OPT] optimize sample code

* [ONNX2TNN][BUG]1. add more check for fuse gemm;

* [CAFFE2ONNX][UPD]1. add Power layer; 2.fix some bugs for Scale layer;

* [CAFFE2ONNX][UPD]1. add missing Power.py;

* [TOOLS]add Tanh layer in caffe2onnx

* [DOC][UPD]1. udpate docker hub message;

* [TNN][OPT] fix issue #65

* [DOCKER][UPD]1. update Dockerfile

* [CONVERTER][BUG] fix issue #94

* [DOCKER][UPD]1. move Dockerfile to TNN_ROOT path;

* [DOCKER][UPD]1. update convert.md;2. BuildDockerImage;

* [ARM]fix pow layer bug when input < 0 ok

* [CONVERTER][BUG] fix issue #94

* [TNN][OPT] modify description

* modify description

* [CONVERTER][BUG] fix issue #94

* [CONVERTER][BUG] fix issue #94

* [CONVERTER][BUG] fix align model failed

* [CONVERTER][OPT] optimize code logic

* [ADD]add pre commit hook

* [ADD]add acc adapter for metal

* [UPD]fix bug of adapter for metal and opencl

* [ONNX2TNN][BUG]1. fix issue #104;

* fix use of undeclared identifier 'status‘’

* TNNtest can load NCNN model with input_name and input_shape

* [BUG]fix status error

* [TNNTEST][UPD]1. add features of specified input shape in TNNTest;

* [ARM][BUG] fix power layer unit test error

* [doc]update website index.rst

* [doc]update front page's techsolution

* [CONVERTER][OPT] fix issue #24

* [CONVERTER][OPT] fix issue #24

* [CONVERTER][OPT] fix issue #24

* [CONVERTER][OPT] fix issue #24

* [CONVERT2TNN][UPD]1. 优化了convert2tnn的输出日志;

* [CONVERT2TNN][UPD]1. 优化了convert2tnn的输出日志;

* add static library demo

* [BENCHMARK][OPT]默认运行model下所有模型

* [ARM]move alloc param to init for binary, bn, add

* [ARM]fc, nchw, reformat alloc param move to init

* [ARM]opt conv reshape

* [TOOLS][BUG] fix model check tool build failed in linux

close #135

* [DOC][UPD] how to update converter's docker image (#134)

* fix: typo

* [OPENCL][BUG] fix compile error when gcc version is below 4.9 (#139)

close #137

* [ARM][CHG] binary op add broadcast in w dim

* [ONNX2TNN][BUG]1.fix issue #141;

* [CONVERTER][ADD] add return code (#143)

* [CONVERTER][ADD] add return code

* [CONVERTER][OPT] optimize code format

* [CONVERTER][BUG] check file's bug

* [CONVERTER][UPD] fix info level

* [CONVERTER][UPD] fix log level

* [CONVERTER][UPD] fix log format

Co-authored-by: ealinli <ealinli@tencent.com>
Co-authored-by: lucasktian <lucasktian@tencent.com>

* [ONNX2TNN][BUG]1. fix issue #125; (#128)

* [CAFFE2ONNX][BUG]1. merge PR #121;

* [BENCHMARK][PATCH]merge benchmark and refactor test

* add travis ci (#130)

* add ci config file

Signed-off-by: seanxcwang <seanxcwang@tencent.com>

* [CI] add ios build

* [CI] fix ios build path error

* [CI] add more build

* [DEL] delete unused badge

* [CI] fix root path error of build scripts

* [CI] fix build ios path error

* change for build linux

* remove debug

Co-authored-by: quinnrong94 <quinnrong@tencent.com>
Co-authored-by: neiltian <neiltian@tencent.com>

* Revert "add travis ci (#130)"

This reverts commit 606bb488836fdcbff17e31d4b27cc25a422cfac3.

* Revert "add travis ci (#130)"

This reverts commit 606bb488836fdcbff17e31d4b27cc25a422cfac3.

* Patch ci (#156)

* Revert "Revert "add travis ci (#130)""

This reverts commit 00acc481f0579467c428ca75b55028126782ae69.

* fix mac build error

* change for macos

* remove unit test

* Patch ci (#156)

* Revert "Revert "add travis ci (#130)""

This reverts commit 00acc481f0579467c428ca75b55028126782ae69.

* fix mac build error

* change for macos

* remove unit test

* [DOC][OPT] optimize doc structure

* [CONVERTER][BUG] protobuf related bug

* fix gnustl compile error (#165)

good

* [ONNX2TNN] fix compability with onnx resize opset 10 and 12+

* fix bugs in ssd model (#168)

* Update caffe2onnx.py

add Scale support

* [TEST][BUG] 1. fix CompareData;

* Feature layer signedmul (#157)

* [CPU][ADD] add signed mul

* [CPU][ADD] add signed mul

* [CPU][UPD] update signed_mul_layer_interpreter

* [CPU][ADD] add signed mul

* [CPU][BUG] implement reshape

* [CPU][UPD]1. add unit test for SignedMul;

* [CPU][UPD]1. make SignedMul more clearly;

* Update cpu_signed_mul_layer_acc.cc

fix bugs, reduce extra compute

* Update cpu_signed_mul_layer_acc.cc

fix signedmul bugs

* [ARM][ADD] add signed mul

* [ARM][UPD] implement using float4

* [ARM][UPD] check data type

* Feature layer signedmul (#164)

* fix bug in signed_mul layer unittest

* add metal acc for SignedMulLayer

* [ARM][UPD] support bfp16 data type

* add opencl signed mul

* fix unit test error for signed mul

Co-authored-by: ealinli <ealinli@tencent.com>
Co-authored-by: liyilin <liyilin@megvii.com>
Co-authored-by: dididi <7722452+di_di_di@user.noreply.gitee.com>
Co-authored-by: darrenyao87 <62542779+darrenyao87@users.noreply.github.com>
Co-authored-by: quinnrong <quinnrong@tencent.com>
Co-authored-by: devandong <67893313+devandong@users.noreply.github.com>
Co-authored-by: neiltian <neiltian@tencent.com>

* [ADD]add relu6 fusion

* remove namespace hardcode tnn

* [ONNX2TNN][BUG]1. fix issue #162; (#163)

* [ARM][BUG] fix reduce op error

* [CONVERTER][BUG] fix input name's bug

* Update Dockerfile

* [CONVERTER][BUG] bug with spaces in path

* [CONVERTER][OPT] remove extra code

* [CONVERTER][OPT] remove extra file

* [CONVERTER][OPT] remove extra code

* [DOC][OPT] optimized document description

* [DOC][OPT] optimized document description

* [DOC][BUG] fix bug in convert doc

Co-authored-by: BUG1989 <248857878@qq.com>
Co-authored-by: tpoisonooo <khj.application@aliyun.com>
Co-authored-by: neiltian <neiltian@tencent.com>
Co-authored-by: darrenyao <darrenyao@tencent.com>
Co-authored-by: darrenyao87 <62542779+darrenyao87@users.noreply.github.com>
Co-authored-by: alohali <alohali@tencent.com>
Co-authored-by: nihui <shuizhuyuanluo@126.com>
Co-authored-by: Tian Kai <lucasktian@tencent.com>
Co-authored-by: ealinli <ealinli@tencent.com>
Co-authored-by: yeliyli <yeliyli@tencent.com>
Co-authored-by: shaundai <shaundai@tencent.com>
Co-authored-by: shaundai-tencent <66760945+shaundai-tencent@users.noreply.github.com>
Co-authored-by: tomguluson92 <314913739@qq.com>
Co-authored-by: dandiding <bluaxe@users.noreply.github.com>
Co-authored-by: Maosquerade <shenpenwang@tencent.com>
Co-authored-by: seanxcwang <seanxcwang@tencent.com>
Co-authored-by: jestyf <jestyf@hotmail.com>
Co-authored-by: NotBad <ysh329@sina.com>
Co-authored-by: Guanmoyu <15651666782@163.com>
Co-authored-by: Shen Shuntian <timshen@tencent.com>
Co-authored-by: seanxcwang <66675860+seanxcwang@users.noreply.github.com>
Co-authored-by: quinnrong94 <quinnrong@tencent.com>
Co-authored-by: neiltian <65950677+neiltian-tencent@users.noreply.github.com>
Co-authored-by: devandong <67893313+devandong@users.noreply.github.com>
Co-authored-by: masterwan96 <64312349+masterwan96@users.noreply.github.com>
Co-authored-by: liyilin <liyilin@megvii.com>
Co-authored-by: dididi <7722452+di_di_di@user.noreply.gitee.com>
Co-authored-by: root <root@ealinli-PC0.tencent.com>